openapi: 3.0.0
info:
  title: Customer API
  description: |
    Customer API used to manage the consumer wallet context.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/GoCartPay/gocart-customer-api/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://api-staging.gocartpay.com
  description: GoCart Staging Environment
- url: https://api.gocartpay.com/
  description: GoCart Production Environment
tags:
- name: Customer
  description: |
    Core customer related API service methods.
- name: Customer Addresses
  description: |
    Managerment of a customer's addresses.
- name: Customer Payment Methods
  description: |
    Management of a customer's payment methods
paths:
  /customers:
    get:
      tags:
      - Customer
      summary: Temp Placeholder
      description: "No public APIs exposed yet, so this endpoint is strictly here\
        \ as a temp placeholder."
      responses:
        "200":
          description: Success
components: {}
